### PR TITLE
Fixed README.md table

### PR DESCRIPTION
**Pull request by DanyaIzm**
Table wasn't displayed correctly and repeated multiple times with the same information

### CODE REVIEW

**Comment by DanyaIzm** [comment]
Repetition of information in the table.

rep

**Comment by DanyaIzm** [comment]
Incorrect markdown table layout.

incorrect table

**Comment by azad-ali786** [comment]
LG. Can you update the PR, I will merge it after.

**Comment by DanyaIzm** [comment]
Updated

**Pull request merged**
